version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: Install coverage
          command: pip install coverage
      - run:
          name: Run tests and collect coverage
          command: coverage run tests.py
      - run:
          name: Upload coverage reports to Codecov
          command: bash <(curl -s https://codecov.io/bash) -u https://stage-web.codecov.dev -F test-12.9.0

workflows:
  version: 2.1
  build-test:
    jobs:
      - build
